# Generated by Django 4.2 on 2023-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
