# Generated by Django 4.2 on 2023-05-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadedfile_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_type',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='local_file_type',
            field=models.CharField(blank=True, choices=[('json', 'JSON'), ('csv', 'CSV'), ('image', 'Image'), ('pdf', 'Document')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='url_file_type',
            field=models.CharField(blank=True, choices=[('mongo', 'MONGO'), ('sql', 'SQL')], max_length=10, null=True),
        ),
    ]
