# Generated by Django 4.2 on 2023-05-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_uploadedfile_password_uploadedfile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='conversion_type',
            field=models.CharField(blank=True, choices=[('TimeSeries', 'Time Series'), ('ToSQL', 'To SQL'), ('LinearReg', 'Linear Regression')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='url_file_type',
            field=models.CharField(blank=True, choices=[('sql', 'SQL'), ('nosql', 'NOSQL')], max_length=10, null=True),
        ),
    ]
