# Generated by Django 4.2 on 2023-05-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_uploadedfile_conversion_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='X_axis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='Y_axis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
