# Generated by Django 4.2 on 2023-05-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_uploadedfile_column_name_uploadedfile_d_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='column_name',
            new_name='mavg_column_name',
        ),
    ]
