# Generated by Django 4.2 on 2023-05-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_column_name_uploadedfile_mavg_column_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='data_column_name',
            new_name='arima_column_name',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='arima_data_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='lags_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='lags_data_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='leads_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='leads_data_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='rolling_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='rolling_data_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='timereg_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='timereg_data_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
