# Generated by Django 4.2 on 2023-05-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_data_column_name_uploadedfile_arima_column_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='local_file_type',
            field=models.CharField(blank=True, choices=[('null', '----'), ('json', 'JSON'), ('csv', 'CSV'), ('image', 'Image'), ('pdf', 'Document')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='url_file_type',
            field=models.CharField(blank=True, choices=[('null', '----'), ('sql', 'SQL'), ('nosql', 'NOSQL')], max_length=10, null=True),
        ),
    ]
