# Generated by Django 4.2 on 2023-05-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_uploadedfile_local_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='convert_type',
            field=models.CharField(blank=True, choices=[('ToSQL', 'To SQL'), ('ToNOSQL', 'To NOSQL')], max_length=10, null=True),
        ),
    ]
