# Generated by Django 4.2 on 2023-05-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_uploadedfile_convert_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='collection_name',
            new_name='collection_name_nosql',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='collection_name_sql',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
