# Generated by Django 4.2 on 2023-05-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_collection_name_uploadedfile_collection_name_nosql_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='sql_db_connection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='sql_db_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='sql_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='sql_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
